version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocritic
    - lll
    - mnd
    - musttag
    - nlreturn
    - noinlineerr
    - revive
    - tagalign
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    sloglint:
      kv-only: false
      attr-only: true
      context: all
      static-msg: true
      key-naming-case: camel
