linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocritic
    - lll
    - mnd
    - musttag
    - nlreturn
    - tagalign
    - testpackage
    - varnamelen
    - wsl
  settings:
    sloglint:
      kv-only: false
      attrs-only: true
      context: all
      static-msg: true
      key-naming-case: camel
